### ISSUE TITLE
Consider separating container from adaptors

### ISSUE THREAD

**Issue by opengeek** [jeremeamia/acclimate-container#14]
Any chance you would consider breaking this into two projects, one for the container implementation and one for the adaptors (or even one per adaptor).  I would love to use this project as a central DI container for a micro-framework project, but having to load all the dev dependencies for any dev project when using the micro-framework is a problem we would like to avoid. Users who want to take advantage of adaptors to other containers may not mind the extra weight, but the burden should not be placed on all users of the container.

**Comment by mnapoli** [comment]
@opengeek I don't see the issue, if you require this package using Composer it will not install all the dev dependencies. This package [only requires container-interop](https://github.com/jeremeamia/acclimate-container/blob/master/composer.json#L16) so that's the only thing that should be installed.

**Comment by opengeek** [comment]
The problem is the micro-framework would be used by many developers who would never need the composite container functionality and every single one of them who wanted to work on a project with this micro-framework would have to load all of those dependencies when working with dev dependencies (i.e. running their project's unit tests) at all.

**Comment by mnapoli** [comment]
> would have to load all of those dependencies when working with dev dependencies

No they wouldn't. Composer will not install the dev dependencies of dependencies.

**Comment by opengeek** [comment]
And that's what I get for running on assumptions rather than trying it. Thanks for the feedback @mnapoli.

**Comment by mnapoli** [comment]
No worries!
