### ISSUE TITLE
Namespace -> dir mapping inconsistent (PSR4 compliance)?

### ISSUE THREAD

**Issue by woodywould** [jeremeamia/acclimate-container#21]
(Apologies in advance if this is some noob error on my part)

**EXPECTED: PSR4 compliance?**
`namespace Acclimate\Container;`
should be found at:
`acclimate-container/src/Acclimate/Container/
`

**ACTUAL:**
`namespace Acclimate\Container;`
Is found at:
[acclimate-container/src/`
](https://github.com/jeremeamia/acclimate-container/blob/master/src/)

**Notes**

Acclimate doesn't seem consistent with PSR4 (http://www.php-fig.org/psr/psr-4/) : 

_"The contiguous sub-namespace names after the "namespace prefix" correspond to a subdirectory within a "base directory", in which the namespace separators represent directory separators. The subdirectory name MUST match the case of the sub-namespace names."_

Other projects, even the PHP DI interop,  map more directly and consistently, for example:
[container-interop/src/Interop/Container/ContainerInterface.php
](https://github.com/container-interop/container-interop/blob/master/src/Interop/Container/ContainerInterface.php)

```
//
namespace Interop\Container;

interface ContainerInterface
{
```
I'm not using (and can't use) composer, so perhaps that's why It's affected me?

(PS: Thanks for making and maintaining this library, very useful!)

**Comment by GrahamCampbell** [comment]
I'm not sure what you mean? It **is** already PSR4 compliant. This compliance is demonstrated by the passing test suite that relies on composer's PSR4 compliant autoloader.

**Comment by GrahamCampbell** [comment]
> should be found at:
> acclimate-container/src/Acclimate/Container/ 

Not true, not that the root folder is `/`, not `acclimate-container/`. That's just the repo name.

**Comment by woodywould** [comment]
As I said, I can't use Composer in my context :(

 Surely for PSR4 compliance there has to be a folder somewhere called Acclimate, with a child folder called Container, and I don't see that when browsing the repo.

Would composer move the contents of /src into the path Acclimate/Container?

**Comment by GrahamCampbell** [comment]
> Surely for PSR4 compliance there has to be a folder somewhere called Acclimate

No, actually there doesn't.

**Comment by jeremeamia** [comment]
PSR-4 allows you to map a namespace prefix to a base directory. If you look in the `composer.json`, the `Acclimate\Container\` namespace prefix is mapped to `src/`. Any PSR-4 compliant autoloader should allow you to do that as well. PSR-0 requires the full directory structure, though, maybe that is why you are confused.

**Comment by woodywould** [comment]
Ok, thanks for clearing that up
Maybe my real ask is to idiot proof the install section of the documentation, 
_"Acclimate supports psr4, but not psr0. If you are installing without Composer, be sure to set the namespace prefix in your own psr4 class loader like so..."_

At your discretion, of course.
Thanks for your responses.
