### ISSUE TITLE
Add Nette\DI

### ISSUE THREAD

**Issue by f3l1x** [jeremeamia/acclimate-container#39]
Great Dependency Injection Container.

https://github.com/nette/di

Compatibily should be great, according to your readme.

**Comment by Sam-Burns** [comment]
@f3l1x I think this is addressed by https://github.com/jeremeamia/acclimate-container/blob/master/src/Adapter/NetteContainerAdapter.php , no?

**Comment by f3l1x** [comment]
@Sam-Burns Oh, I'm sorry. I didn't notice.

**Comment by Sam-Burns** [comment]
No problem at all.  Do let us know if you have any issues using it.
